### ISSUE TITLE
No new tags can be added when colors are exhausted

### ISSUE THREAD

**Issue by jwezel** [bookmanize/bookmanize.github.io#5]
When all colors have been used, no new tags can be added.

There should always be a way to specify a custom color.

**Comment by ohmycaptainnemo** [comment]
I second jwezel. I really like this tool. I was quite happily making lots of tags until I could not anymore and I was surprised.
I would suggest:

Picking up a colour for a tag should not be compulsory. All tags could default to a specific colour when created and the user then can have the option of picking their colour of interest. The colour of interest does not need to be unique necessarily. There could exist tags with duplicate colours. The pool of available colours to the user does not need to shrink in size as the user could decide to pick the same colour again. This way, the responsibility of picking a colour and making it unique or not is now purely the task of the user. It is totally up to the programmer to have a limited range of colours available to the user or have some other creative way of providing a variety of different colours.

What are your thoughts on this?

**Comment by bookmanize** [comment]
Hi @jwezel @ohmycaptainnemo 
Thank you for your feedback

@ohmycaptainnemo This is a good idea. We will add this to the next build

**Comment by bookmanize** [comment]
Done in v1.6.5
