### ISSUE TITLE
[Feature] Disable Context Menu

### ISSUE THREAD

**Issue by Son-Vegitto** [bookmanize/bookmanize.github.io#8]
Hello,

Is it possible to add the ability to disable/enable the context menu/right click?

If not, is there a way to manually disable it?

Thank you

**Comment by bookmanize** [comment]
@Son-Vegitto Added setting for disabling in version 1.6.26

<img width="1721" alt="Screenshot 1" src="https://github.com/bookmanize/bookmanize.github.io/assets/72801613/13a84cca-0fba-4b8a-a379-1523ff28e5fb">
